import { TRACKS } from './paths.js';

const GEN_NOTE = '<!-- Generated by scripts/validate-scenarios.sh — do not edit by hand. -->';
export const README_BEGIN = '<!-- BEGIN SCENARIOS -->';
export const README_END = '<!-- END SCENARIOS -->';

export function kebabToCamel(s) {
  return s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function sortById(scenarios) {
  return scenarios.slice().sort((a, b) => a.id.localeCompare(b.id));
}

function renderTable(scenarios, linkPrefix = '') {
  const rows = sortById(scenarios).map((s) => {
    const m = s.manifest;
    const mins = m.estimatedMinutes ? `${m.estimatedMinutes}m` : '—';
    const diff = m.difficulty ?? '—';
    return `| [${m.title}](${linkPrefix}${s.id}/) | ${m.severity} | ${mins} | ${diff} | ${m.summary} |`;
  });
  return [
    '| Scenario | Severity | Est. | Difficulty | Summary |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

export function renderIndex(track, scenarios) {
  return [`# ${track.toUpperCase()} Scenarios`, '', GEN_NOTE, '', renderTable(scenarios, ''), ''].join('\n');
}

export function renderReadmeBlock(scenarios) {
  return [README_BEGIN, GEN_NOTE, '', renderTable(scenarios, 'scenarios/'), '', README_END].join('\n');
}

export function renderAggregator(track, scenarios) {
  const cfg = TRACKS[track];
  if (!cfg) throw new Error(`Unknown track: ${track}`);
  const withAlerts = sortById(scenarios.filter((s) => s.manifest.signal?.alertModule));

  const header = [
    '// GENERATED by scripts/scenario-tools — do not edit by hand.',
    `// Aggregates per-scenario alert modules for the ${track} track.`,
    '',
    "@description('Azure region for alert resources')",
    'param location string',
    '',
    "@description('Base workload name for resource naming')",
    'param workloadName string',
    '',
    "@description('Resource tags')",
    'param tags object',
    '',
    "@description('Scope resource ID each scenario alert binds to')",
    `param ${cfg.scopeParam} string`,
    '',
  ];

  const modules = withAlerts.flatMap((s) => {
    const sym = `${kebabToCamel(s.id)}Alert`;
    const rel = `../../../scenarios/${s.id}/${s.manifest.signal.alertModule}`;
    return [
      `module ${sym} '${rel}' = {`,
      `  name: 'alert-${s.id}'`,
      '  params: {',
      '    location: location',
      '    workloadName: workloadName',
      '    tags: tags',
      `    scopeResourceId: ${cfg.scopeParam}`,
      '  }',
      '}',
      '',
    ];
  });

  return [...header, ...modules].join('\n');
}
