// GENERATED by scripts/scenario-tools — do not edit by hand.
// Aggregates per-scenario alert modules for the vm track.

@description('Azure region for alert resources')
param location string

@description('Base workload name for resource naming')
param workloadName string

@description('Resource tags')
param tags object

@description('Scope resource ID each scenario alert binds to')
param logAnalyticsResourceId string

module cpuRunawayAlert '../../../scenarios/cpu-runaway/alert.bicep' = {
  name: 'alert-cpu-runaway'
  params: {
    location: location
    workloadName: workloadName
    tags: tags
    scopeResourceId: logAnalyticsResourceId
  }
}

module diskFullAlert '../../../scenarios/disk-full/alert.bicep' = {
  name: 'alert-disk-full'
  params: {
    location: location
    workloadName: workloadName
    tags: tags
    scopeResourceId: logAnalyticsResourceId
  }
}

module iisAppPoolAlert '../../../scenarios/iis-app-pool/alert.bicep' = {
  name: 'alert-iis-app-pool'
  params: {
    location: location
    workloadName: workloadName
    tags: tags
    scopeResourceId: logAnalyticsResourceId
  }
}
