// GENERATED by scripts/scenario-tools — do not edit by hand.
// Aggregates per-scenario alert modules for the aks track.

@description('Azure region for alert resources')
param location string

@description('Base workload name for resource naming')
param workloadName string

@description('Resource tags')
param tags object

@description('Scope resource ID each scenario alert binds to')
param clusterId string

module cosmosRbacRemovalAlert '../../../scenarios/cosmos-rbac-removal/alert.bicep' = {
  name: 'alert-cosmos-rbac-removal'
  params: {
    location: location
    workloadName: workloadName
    tags: tags
    scopeResourceId: clusterId
  }
}
